name: movie_recommendation_app
description: "A new Flutter project."
# Prevent accidental publication to pub.dev
publish_to: 'none'

# Version information
version: 1.0.0+1

# Environment configuration
environment:
  sdk: ">=3.6.0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0 # For API calls
  provider: ^6.0.0 # For state management
  cupertino_icons: ^1.0.8 # For iOS-style icons

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Recommended lints for better coding practices

# Flutter-specific configuration
flutter:
  uses-material-design: true # Enable Material Design icons

  # Uncomment and add assets as needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment to add custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
